version: "3"
services:
  nextdocker:
    build: ./
  nginx:
    build: ./nginx
    ports:
      - 80:80
# version: "3"
#
# services:
#   begeby:
#     container_name: begeby
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     image: begeby
#     ports:
#       - "3000:3000"
#     volumes:
#       - ".:/app"
#       - "/app/node_modules"
#       - "/app/.next"
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#   nginx:
#     build: ./nginx
#     ports:
#       - 80:80
#     networks:
#       begeby-network:

# networks:
#   begeby-network:
#     external: true
